DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS chats_members;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS system_state;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS chat_role;
DROP TYPE IF EXISTS chat_kind;
DROP TYPE IF EXISTS user_role;
